/*****************************************************************************
 * MacLCWatchCollectionsPool.m: the built-in pool of The Edit's collections
 *****************************************************************************
 * Copyright (C) 2026 Hazen Studio
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston MA 02110-1301, USA.
 *****************************************************************************/

/* Generated from .agents/reports/discovery-fixtures/edit-pool.json (titles
 * and years checked against Wikipedia). Titles are matched against the
 * installed catalog add-ons at run time (MacLCWatchDiscovery). */
#import <Foundation/Foundation.h>

NSData *MacLCWatchCollectionsPoolData(void);

NSData *MacLCWatchCollectionsPoolData(void)
{
    static const char json[] =
    "{\"version\":1,\"collections\":[{\"id\":\"best-picture-winners\",\"title\":\"Best Picture Winners\",\"subtitle\":\""
    "Sixteen winners of the Academy Award for Best Picture since 2000.\",\"kind\":\"award\",\"symbol\":\"trophy.f"
    "ill\",\"tint\":\"yellow\",\"source\":\"https://en.wikipedia.org/wiki/Academy_Award_for_Best_Picture\",\"items\""
    ":[{\"title\":\"Gladiator\",\"year\":2000,\"type\":\"movie\"},{\"title\":\"A Beautiful Mind\",\"year\":2001,\"type\":\"m"
    "ovie\"},{\"title\":\"Chicago\",\"year\":2002,\"type\":\"movie\"},{\"title\":\"The Lord of the Rings: The Return of"
    " the King\",\"year\":2003,\"type\":\"movie\"},{\"title\":\"Million Dollar Baby\",\"year\":2004,\"type\":\"movie\"},{\""
    "title\":\"The Departed\",\"year\":2006,\"type\":\"movie\"},{\"title\":\"No Country for Old Men\",\"year\":2007,\"typ"
    "e\":\"movie\"},{\"title\":\"Slumdog Millionaire\",\"year\":2008,\"type\":\"movie\"},{\"title\":\"The King's Speech\","
    "\"year\":2010,\"type\":\"movie\"},{\"title\":\"The Artist\",\"year\":2011,\"type\":\"movie\"},{\"title\":\"Argo\",\"year\""
    ":2012,\"type\":\"movie\"},{\"title\":\"12 Years a Slave\",\"year\":2013,\"type\":\"movie\"},{\"title\":\"Spotlight\",\""
    "year\":2015,\"type\":\"movie\"},{\"title\":\"Moonlight\",\"year\":2016,\"type\":\"movie\"},{\"title\":\"Parasite\",\"yea"
    "r\":2019,\"type\":\"movie\"},{\"title\":\"Oppenheimer\",\"year\":2023,\"type\":\"movie\"}]},{\"id\":\"palme-dor-winner"
    "s\",\"title\":\"Palme d'Or Winners\",\"subtitle\":\"Fifteen winners of the Cannes Film Festival’s top prize "
    "since 2000.\",\"kind\":\"award\",\"symbol\":\"sparkles\",\"tint\":\"orange\",\"source\":\"https://en.wikipedia.org/w"
    "iki/Palme_d%27Or\",\"items\":[{\"title\":\"Dancer in the Dark\",\"year\":2000,\"type\":\"movie\"},{\"title\":\"The P"
    "ianist\",\"year\":2002,\"type\":\"movie\"},{\"title\":\"The Wind That Shakes the Barley\",\"year\":2006,\"type\":\"m"
    "ovie\"},{\"title\":\"4 Months, 3 Weeks and 2 Days\",\"year\":2007,\"type\":\"movie\"},{\"title\":\"The Class\",\"yea"
    "r\":2008,\"type\":\"movie\"},{\"title\":\"The White Ribbon\",\"year\":2009,\"type\":\"movie\"},{\"title\":\"Uncle Boon"
    "mee Who Can Recall His Past Lives\",\"year\":2010,\"type\":\"movie\"},{\"title\":\"The Tree of Life\",\"year\":20"
    "11,\"type\":\"movie\"},{\"title\":\"Amour\",\"year\":2012,\"type\":\"movie\"},{\"title\":\"Blue Is the Warmest Colour"
    "\",\"year\":2013,\"type\":\"movie\"},{\"title\":\"Winter Sleep\",\"year\":2014,\"type\":\"movie\"},{\"title\":\"I, Danie"
    "l Blake\",\"year\":2016,\"type\":\"movie\"},{\"title\":\"The Square\",\"year\":2017,\"type\":\"movie\"},{\"title\":\"Sho"
    "plifters\",\"year\":2018,\"type\":\"movie\"},{\"title\":\"Anatomy of a Fall\",\"year\":2023,\"type\":\"movie\"}]},{\"i"
    "d\":\"best-international-feature\",\"title\":\"Best International Feature\",\"subtitle\":\"Winners of the Acad"
    "emy Award for Best International Feature Film.\",\"kind\":\"award\",\"symbol\":\"globe.europe.africa.fill\",\""
    "tint\":\"teal\",\"source\":\"https://en.wikipedia.org/wiki/Academy_Award_for_Best_International_Feature_Fi"
    "lm\",\"items\":[{\"title\":\"Crouching Tiger, Hidden Dragon\",\"year\":2000,\"type\":\"movie\"},{\"title\":\"No Man'"
    "s Land\",\"year\":2001,\"type\":\"movie\"},{\"title\":\"The Sea Inside\",\"year\":2004,\"type\":\"movie\"},{\"title\":\""
    "The Lives of Others\",\"year\":2006,\"type\":\"movie\"},{\"title\":\"The Counterfeiters\",\"year\":2007,\"type\":\"m"
    "ovie\"},{\"title\":\"Departures\",\"year\":2008,\"type\":\"movie\"},{\"title\":\"The Secret in Their Eyes\",\"year\":"
    "2009,\"type\":\"movie\"},{\"title\":\"A Separation\",\"year\":2011,\"type\":\"movie\"},{\"title\":\"The Great Beauty\""
    ",\"year\":2013,\"type\":\"movie\"},{\"title\":\"Ida\",\"year\":2013,\"type\":\"movie\"},{\"title\":\"Son of Saul\",\"year"
    "\":2015,\"type\":\"movie\"},{\"title\":\"A Fantastic Woman\",\"year\":2017,\"type\":\"movie\"},{\"title\":\"Roma\",\"yea"
    "r\":2018,\"type\":\"movie\"},{\"title\":\"Another Round\",\"year\":2020,\"type\":\"movie\"},{\"title\":\"Drive My Car\""
    ",\"year\":2021,\"type\":\"movie\"}]},{\"id\":\"bafta-best-film\",\"title\":\"BAFTA Best Film Winners\",\"subtitle\":"
    "\"British Academy Film Award recipients for Best Film across the decades.\",\"kind\":\"award\",\"symbol\":\"t"
    "heatermasks.fill\",\"tint\":\"purple\",\"source\":\"https://en.wikipedia.org/wiki/BAFTA_Award_for_Best_Film\""
    ",\"items\":[{\"title\":\"Goodfellas\",\"year\":1990,\"type\":\"movie\"},{\"title\":\"Schindler's List\",\"year\":1993,"
    "\"type\":\"movie\"},{\"title\":\"The Lord of the Rings: The Fellowship of the Ring\",\"year\":2001,\"type\":\"mov"
    "ie\"},{\"title\":\"The Aviator\",\"year\":2004,\"type\":\"movie\"},{\"title\":\"Brokeback Mountain\",\"year\":2005,\"t"
    "ype\":\"movie\"},{\"title\":\"The Queen\",\"year\":2006,\"type\":\"movie\"},{\"title\":\"Atonement\",\"year\":2007,\"typ"
    "e\":\"movie\"},{\"title\":\"Boyhood\",\"year\":2014,\"type\":\"movie\"},{\"title\":\"The Revenant\",\"year\":2015,\"type"
    "\":\"movie\"},{\"title\":\"La La Land\",\"year\":2016,\"type\":\"movie\"},{\"title\":\"Three Billboards Outside Ebbi"
    "ng, Missouri\",\"year\":2017,\"type\":\"movie\"},{\"title\":\"1917\",\"year\":2019,\"type\":\"movie\"},{\"title\":\"Noma"
    "dland\",\"year\":2020,\"type\":\"movie\"},{\"title\":\"The Power of the Dog\",\"year\":2021,\"type\":\"movie\"},{\"tit"
    "le\":\"All Quiet on the Western Front\",\"year\":2022,\"type\":\"movie\"}]},{\"id\":\"golden-lion-winners\",\"titl"
    "e\":\"Golden Lion Winners\",\"subtitle\":\"Fifteen winners of the Venice Film Festival’s Golden Lion since"
    " 2001.\",\"kind\":\"award\",\"symbol\":\"crown.fill\",\"tint\":\"orange\",\"source\":\"https://en.wikipedia.org/wiki"
    "/Golden_Lion\",\"items\":[{\"title\":\"Monsoon Wedding\",\"year\":2001,\"type\":\"movie\"},{\"title\":\"The Magdalen"
    "e Sisters\",\"year\":2002,\"type\":\"movie\"},{\"title\":\"The Return\",\"year\":2003,\"type\":\"movie\"},{\"title\":\"V"
    "era Drake\",\"year\":2004,\"type\":\"movie\"},{\"title\":\"Still Life\",\"year\":2006,\"type\":\"movie\"},{\"title\":\"L"
    "ust, Caution\",\"year\":2007,\"type\":\"movie\"},{\"title\":\"The Wrestler\",\"year\":2008,\"type\":\"movie\"},{\"titl"
    "e\":\"Lebanon\",\"year\":2009,\"type\":\"movie\"},{\"title\":\"Somewhere\",\"year\":2010,\"type\":\"movie\"},{\"title\":\""
    "Pietà\",\"year\":2012,\"type\":\"movie\"},{\"title\":\"Roma\",\"year\":2018,\"type\":\"movie\"},{\"title\":\"Joker\",\"yea"
    "r\":2019,\"type\":\"movie\"},{\"title\":\"Happening\",\"year\":2021,\"type\":\"movie\"},{\"title\":\"All the Beauty an"
    "d the Bloodshed\",\"year\":2022,\"type\":\"movie\"},{\"title\":\"Poor Things\",\"year\":2023,\"type\":\"movie\"}]},{\""
    "id\":\"emmy-outstanding-drama\",\"title\":\"Emmy Drama Series Winners\",\"subtitle\":\"Recipients of the Prime"
    "time Emmy Award for Outstanding Drama Series.\",\"kind\":\"award\",\"symbol\":\"sparkles.tv.fill\",\"tint\":\"bl"
    "ue\",\"source\":\"https://en.wikipedia.org/wiki/Primetime_Emmy_Award_for_Outstanding_Drama_Series\",\"item"
    "s\":[{\"title\":\"Hill Street Blues\",\"year\":1981,\"type\":\"series\"},{\"title\":\"L.A. Law\",\"year\":1986,\"type\""
    ":\"series\"},{\"title\":\"Law & Order\",\"year\":1990,\"type\":\"series\"},{\"title\":\"NYPD Blue\",\"year\":1993,\"typ"
    "e\":\"series\"},{\"title\":\"ER\",\"year\":1994,\"type\":\"series\"},{\"title\":\"The Sopranos\",\"year\":1999,\"type\":\""
    "series\"},{\"title\":\"The West Wing\",\"year\":1999,\"type\":\"series\"},{\"title\":\"24\",\"year\":2001,\"type\":\"ser"
    "ies\"},{\"title\":\"Lost\",\"year\":2004,\"type\":\"series\"},{\"title\":\"Mad Men\",\"year\":2007,\"type\":\"series\"},{"
    "\"title\":\"Breaking Bad\",\"year\":2008,\"type\":\"series\"},{\"title\":\"Game of Thrones\",\"year\":2011,\"type\":\"s"
    "eries\"},{\"title\":\"Homeland\",\"year\":2011,\"type\":\"series\"},{\"title\":\"The Crown\",\"year\":2016,\"type\":\"se"
    "ries\"},{\"title\":\"Succession\",\"year\":2018,\"type\":\"series\"}]},{\"id\":\"emmy-outstanding-comedy\",\"title\":"
    "\"Emmy Comedy Series Winners\",\"subtitle\":\"Recipients of the Primetime Emmy Award for Outstanding Come"
    "dy Series.\",\"kind\":\"award\",\"symbol\":\"face.smiling.fill\",\"tint\":\"pink\",\"source\":\"https://en.wikipedia"
    ".org/wiki/Primetime_Emmy_Award_for_Outstanding_Comedy_Series\",\"items\":[{\"title\":\"Cheers\",\"year\":1982"
    ",\"type\":\"series\"},{\"title\":\"The Golden Girls\",\"year\":1985,\"type\":\"series\"},{\"title\":\"Seinfeld\",\"year"
    "\":1989,\"type\":\"series\"},{\"title\":\"Frasier\",\"year\":1993,\"type\":\"series\"},{\"title\":\"Friends\",\"year\":19"
    "94,\"type\":\"series\"},{\"title\":\"Everybody Loves Raymond\",\"year\":1996,\"type\":\"series\"},{\"title\":\"Will &"
    " Grace\",\"year\":1998,\"type\":\"series\"},{\"title\":\"Sex and the City\",\"year\":1998,\"type\":\"series\"},{\"titl"
    "e\":\"Arrested Development\",\"year\":2003,\"type\":\"series\"},{\"title\":\"30 Rock\",\"year\":2006,\"type\":\"series"
    "\"},{\"title\":\"Modern Family\",\"year\":2009,\"type\":\"series\"},{\"title\":\"Veep\",\"year\":2012,\"type\":\"series\""
    "},{\"title\":\"Fleabag\",\"year\":2016,\"type\":\"series\"},{\"title\":\"Ted Lasso\",\"year\":2020,\"type\":\"series\"},"
    "{\"title\":\"The Bear\",\"year\":2022,\"type\":\"series\"}]},{\"id\":\"christopher-nolan-films\",\"title\":\"Christop"
    "her Nolan Films\",\"subtitle\":\"Feature films directed by British-American filmmaker Christopher Nolan."
    "\",\"kind\":\"director\",\"symbol\":\"film.fill\",\"tint\":\"indigo\",\"source\":\"https://en.wikipedia.org/wiki/Chr"
    "istopher_Nolan_filmography\",\"items\":[{\"title\":\"Following\",\"year\":1998,\"type\":\"movie\"},{\"title\":\"Meme"
    "nto\",\"year\":2000,\"type\":\"movie\"},{\"title\":\"Insomnia\",\"year\":2002,\"type\":\"movie\"},{\"title\":\"Batman Be"
    "gins\",\"year\":2005,\"type\":\"movie\"},{\"title\":\"The Prestige\",\"year\":2006,\"type\":\"movie\"},{\"title\":\"The "
    "Dark Knight\",\"year\":2008,\"type\":\"movie\"},{\"title\":\"Inception\",\"year\":2010,\"type\":\"movie\"},{\"title\":\""
    "The Dark Knight Rises\",\"year\":2012,\"type\":\"movie\"},{\"title\":\"Interstellar\",\"year\":2014,\"type\":\"movie"
    "\"},{\"title\":\"Dunkirk\",\"year\":2017,\"type\":\"movie\"},{\"title\":\"Tenet\",\"year\":2020,\"type\":\"movie\"},{\"tit"
    "le\":\"Oppenheimer\",\"year\":2023,\"type\":\"movie\"}]},{\"id\":\"hayao-miyazaki-films\",\"title\":\"Hayao Miyazaki"
    " Films\",\"subtitle\":\"Enchanting animated feature films directed by anime master Hayao Miyazaki.\",\"kin"
    "d\":\"director\",\"symbol\":\"wind\",\"tint\":\"mint\",\"source\":\"https://en.wikipedia.org/wiki/Hayao_Miyazaki_f"
    "ilmography\",\"items\":[{\"title\":\"The Castle of Cagliostro\",\"year\":1979,\"type\":\"movie\"},{\"title\":\"Nausi"
    "caä of the Valley of the Wind\",\"year\":1984,\"type\":\"movie\"},{\"title\":\"Castle in the Sky\",\"year\":1986,"
    "\"type\":\"movie\"},{\"title\":\"My Neighbor Totoro\",\"year\":1988,\"type\":\"movie\"},{\"title\":\"Kiki's Delivery "
    "Service\",\"year\":1989,\"type\":\"movie\"},{\"title\":\"Porco Rosso\",\"year\":1992,\"type\":\"movie\"},{\"title\":\"Pr"
    "incess Mononoke\",\"year\":1997,\"type\":\"movie\"},{\"title\":\"Spirited Away\",\"year\":2001,\"type\":\"movie\"},{\""
    "title\":\"Howl's Moving Castle\",\"year\":2004,\"type\":\"movie\"},{\"title\":\"Ponyo\",\"year\":2008,\"type\":\"movie"
    "\"},{\"title\":\"The Wind Rises\",\"year\":2013,\"type\":\"movie\"},{\"title\":\"The Boy and the Heron\",\"year\":202"
    "3,\"type\":\"movie\"}]},{\"id\":\"martin-scorsese-films\",\"title\":\"Martin Scorsese Films\",\"subtitle\":\"Signat"
    "ure feature films directed by cinema icon Martin Scorsese.\",\"kind\":\"director\",\"symbol\":\"person.crop."
    "rectangle.fill\",\"tint\":\"red\",\"source\":\"https://en.wikipedia.org/wiki/Martin_Scorsese_filmography\",\"i"
    "tems\":[{\"title\":\"Mean Streets\",\"year\":1973,\"type\":\"movie\"},{\"title\":\"Taxi Driver\",\"year\":1976,\"type\""
    ":\"movie\"},{\"title\":\"Raging Bull\",\"year\":1980,\"type\":\"movie\"},{\"title\":\"The King of Comedy\",\"year\":19"
    "82,\"type\":\"movie\"},{\"title\":\"After Hours\",\"year\":1985,\"type\":\"movie\"},{\"title\":\"Goodfellas\",\"year\":1"
    "990,\"type\":\"movie\"},{\"title\":\"The Age of Innocence\",\"year\":1993,\"type\":\"movie\"},{\"title\":\"Casino\",\"y"
    "ear\":1995,\"type\":\"movie\"},{\"title\":\"Gangs of New York\",\"year\":2002,\"type\":\"movie\"},{\"title\":\"The Avi"
    "ator\",\"year\":2004,\"type\":\"movie\"},{\"title\":\"The Departed\",\"year\":2006,\"type\":\"movie\"},{\"title\":\"Shut"
    "ter Island\",\"year\":2010,\"type\":\"movie\"},{\"title\":\"Hugo\",\"year\":2011,\"type\":\"movie\"},{\"title\":\"The Wo"
    "lf of Wall Street\",\"year\":2013,\"type\":\"movie\"},{\"title\":\"Killers of the Flower Moon\",\"year\":2023,\"ty"
    "pe\":\"movie\"}]},{\"id\":\"stanley-kubrick-films\",\"title\":\"Stanley Kubrick Films\",\"subtitle\":\"Groundbreak"
    "ing and visionary feature films directed by Stanley Kubrick.\",\"kind\":\"director\",\"symbol\":\"eye.fill\","
    "\"tint\":\"brown\",\"source\":\"https://en.wikipedia.org/wiki/Stanley_Kubrick_filmography\",\"items\":[{\"title"
    "\":\"Fear and Desire\",\"year\":1953,\"type\":\"movie\"},{\"title\":\"Killer's Kiss\",\"year\":1955,\"type\":\"movie\"}"
    ",{\"title\":\"The Killing\",\"year\":1956,\"type\":\"movie\"},{\"title\":\"Paths of Glory\",\"year\":1957,\"type\":\"mo"
    "vie\"},{\"title\":\"Spartacus\",\"year\":1960,\"type\":\"movie\"},{\"title\":\"Lolita\",\"year\":1962,\"type\":\"movie\"}"
    ",{\"title\":\"Dr. Strangelove\",\"year\":1964,\"type\":\"movie\"},{\"title\":\"2001: A Space Odyssey\",\"year\":1968"
    ",\"type\":\"movie\"},{\"title\":\"A Clockwork Orange\",\"year\":1971,\"type\":\"movie\"},{\"title\":\"Barry Lyndon\",\""
    "year\":1975,\"type\":\"movie\"},{\"title\":\"The Shining\",\"year\":1980,\"type\":\"movie\"},{\"title\":\"Full Metal J"
    "acket\",\"year\":1987,\"type\":\"movie\"},{\"title\":\"Eyes Wide Shut\",\"year\":1999,\"type\":\"movie\"}]},{\"id\":\"pi"
    "xar-animation\",\"title\":\"Pixar Animation Studios\",\"subtitle\":\"Beloved CGI-animated feature films prod"
    "uced by Pixar Animation Studios.\",\"kind\":\"studio\",\"symbol\":\"lamp.desk.fill\",\"tint\":\"cyan\",\"source\":\""
    "https://en.wikipedia.org/wiki/List_of_Pixar_films\",\"items\":[{\"title\":\"Toy Story\",\"year\":1995,\"type\":"
    "\"movie\"},{\"title\":\"A Bug's Life\",\"year\":1998,\"type\":\"movie\"},{\"title\":\"Toy Story 2\",\"year\":1999,\"typ"
    "e\":\"movie\"},{\"title\":\"Monsters, Inc.\",\"year\":2001,\"type\":\"movie\"},{\"title\":\"Finding Nemo\",\"year\":200"
    "3,\"type\":\"movie\"},{\"title\":\"The Incredibles\",\"year\":2004,\"type\":\"movie\"},{\"title\":\"Cars\",\"year\":2006"
    ",\"type\":\"movie\"},{\"title\":\"Ratatouille\",\"year\":2007,\"type\":\"movie\"},{\"title\":\"WALL-E\",\"year\":2008,\"t"
    "ype\":\"movie\"},{\"title\":\"Up\",\"year\":2009,\"type\":\"movie\"},{\"title\":\"Toy Story 3\",\"year\":2010,\"type\":\"m"
    "ovie\"},{\"title\":\"Inside Out\",\"year\":2015,\"type\":\"movie\"},{\"title\":\"Coco\",\"year\":2017,\"type\":\"movie\"}"
    ",{\"title\":\"Soul\",\"year\":2020,\"type\":\"movie\"},{\"title\":\"Luca\",\"year\":2021,\"type\":\"movie\"},{\"title\":\"T"
    "urning Red\",\"year\":2022,\"type\":\"movie\"}]},{\"id\":\"studio-ghibli-films\",\"title\":\"Studio Ghibli Films\","
    "\"subtitle\":\"Hand-drawn animated masterpieces created by Japan's famed Studio Ghibli.\",\"kind\":\"studio"
    "\",\"symbol\":\"leaf.fill\",\"tint\":\"green\",\"source\":\"https://en.wikipedia.org/wiki/List_of_Studio_Ghibli_"
    "works\",\"items\":[{\"title\":\"Castle in the Sky\",\"year\":1986,\"type\":\"movie\"},{\"title\":\"Grave of the Fire"
    "flies\",\"year\":1988,\"type\":\"movie\"},{\"title\":\"My Neighbor Totoro\",\"year\":1988,\"type\":\"movie\"},{\"title"
    "\":\"Kiki's Delivery Service\",\"year\":1989,\"type\":\"movie\"},{\"title\":\"Only Yesterday\",\"year\":1991,\"type\""
    ":\"movie\"},{\"title\":\"Porco Rosso\",\"year\":1992,\"type\":\"movie\"},{\"title\":\"Pom Poko\",\"year\":1994,\"type\":"
    "\"movie\"},{\"title\":\"Whisper of the Heart\",\"year\":1995,\"type\":\"movie\"},{\"title\":\"Princess Mononoke\",\"y"
    "ear\":1997,\"type\":\"movie\"},{\"title\":\"Spirited Away\",\"year\":2001,\"type\":\"movie\"},{\"title\":\"Howl's Movi"
    "ng Castle\",\"year\":2004,\"type\":\"movie\"},{\"title\":\"Ponyo\",\"year\":2008,\"type\":\"movie\"},{\"title\":\"The Se"
    "cret World of Arrietty\",\"year\":2010,\"type\":\"movie\"},{\"title\":\"The Tale of the Princess Kaguya\",\"year"
    "\":2013,\"type\":\"movie\"},{\"title\":\"The Boy and the Heron\",\"year\":2023,\"type\":\"movie\"}]},{\"id\":\"public-"
    "domain-classics\",\"title\":\"Public Domain Classics\",\"subtitle\":\"Enduring cinema landmarks now freely a"
    "vailable in the US public domain.\",\"kind\":\"theme\",\"symbol\":\"books.vertical.fill\",\"tint\":\"brown\",\"sou"
    "rce\":\"https://en.wikipedia.org/wiki/List_of_films_in_the_public_domain_in_the_United_States\",\"items\""
    ":[{\"title\":\"The Cabinet of Dr. Caligari\",\"year\":1920,\"type\":\"movie\"},{\"title\":\"The Kid\",\"year\":1921,"
    "\"type\":\"movie\"},{\"title\":\"Nosferatu\",\"year\":1922,\"type\":\"movie\"},{\"title\":\"Safety Last!\",\"year\":1923"
    ",\"type\":\"movie\"},{\"title\":\"Sherlock Jr.\",\"year\":1924,\"type\":\"movie\"},{\"title\":\"The Gold Rush\",\"year\""
    ":1925,\"type\":\"movie\"},{\"title\":\"The Phantom of the Opera\",\"year\":1925,\"type\":\"movie\"},{\"title\":\"Batt"
    "leship Potemkin\",\"year\":1925,\"type\":\"movie\"},{\"title\":\"The General\",\"year\":1926,\"type\":\"movie\"},{\"ti"
    "tle\":\"Metropolis\",\"year\":1927,\"type\":\"movie\"},{\"title\":\"Steamboat Bill, Jr.\",\"year\":1928,\"type\":\"mov"
    "ie\"},{\"title\":\"A Star Is Born\",\"year\":1937,\"type\":\"movie\"},{\"title\":\"His Girl Friday\",\"year\":1940,\"t"
    "ype\":\"movie\"},{\"title\":\"Charade\",\"year\":1963,\"type\":\"movie\"},{\"title\":\"Night of the Living Dead\",\"ye"
    "ar\":1968,\"type\":\"movie\"}]},{\"id\":\"mind-bending-sci-fi\",\"title\":\"Mind-Bending Sci-Fi\",\"subtitle\":\"Tho"
    "ught-provoking science fiction that challenges reality and perception.\",\"kind\":\"theme\",\"symbol\":\"bra"
    "in.head.profile\",\"tint\":\"purple\",\"source\":null,\"items\":[{\"title\":\"2001: A Space Odyssey\",\"year\":1968"
    ",\"type\":\"movie\"},{\"title\":\"Solaris\",\"year\":1972,\"type\":\"movie\"},{\"title\":\"Blade Runner\",\"year\":1982,"
    "\"type\":\"movie\"},{\"title\":\"12 Monkeys\",\"year\":1995,\"type\":\"movie\"},{\"title\":\"The Matrix\",\"year\":1999,"
    "\"type\":\"movie\"},{\"title\":\"Donnie Darko\",\"year\":2001,\"type\":\"movie\"},{\"title\":\"Minority Report\",\"year"
    "\":2002,\"type\":\"movie\"},{\"title\":\"Eternal Sunshine of the Spotless Mind\",\"year\":2004,\"type\":\"movie\"},"
    "{\"title\":\"Children of Men\",\"year\":2006,\"type\":\"movie\"},{\"title\":\"Inception\",\"year\":2010,\"type\":\"movi"
    "e\"},{\"title\":\"Interstellar\",\"year\":2014,\"type\":\"movie\"},{\"title\":\"Ex Machina\",\"year\":2014,\"type\":\"mo"
    "vie\"},{\"title\":\"Arrival\",\"year\":2016,\"type\":\"movie\"},{\"title\":\"Blade Runner 2049\",\"year\":2017,\"type\""
    ":\"movie\"},{\"title\":\"Annihilation\",\"year\":2018,\"type\":\"movie\"}]},{\"id\":\"heist-films\",\"title\":\"Heist F"
    "ilms\",\"subtitle\":\"High-stakes robberies, intricate plans, and daring criminal capers.\",\"kind\":\"theme"
    "\",\"symbol\":\"lock.open.fill\",\"tint\":\"orange\",\"source\":null,\"items\":[{\"title\":\"The Asphalt Jungle\",\"ye"
    "ar\":1950,\"type\":\"movie\"},{\"title\":\"Rififi\",\"year\":1955,\"type\":\"movie\"},{\"title\":\"The Killing\",\"year\""
    ":1956,\"type\":\"movie\"},{\"title\":\"The Italian Job\",\"year\":1969,\"type\":\"movie\"},{\"title\":\"The Sting\",\"y"
    "ear\":1973,\"type\":\"movie\"},{\"title\":\"Dog Day Afternoon\",\"year\":1975,\"type\":\"movie\"},{\"title\":\"Reservo"
    "ir Dogs\",\"year\":1992,\"type\":\"movie\"},{\"title\":\"Heat\",\"year\":1995,\"type\":\"movie\"},{\"title\":\"The Usual"
    " Suspects\",\"year\":1995,\"type\":\"movie\"},{\"title\":\"Lock, Stock and Two Smoking Barrels\",\"year\":1998,\"t"
    "ype\":\"movie\"},{\"title\":\"Snatch\",\"year\":2000,\"type\":\"movie\"},{\"title\":\"Ocean's Eleven\",\"year\":2001,\"t"
    "ype\":\"movie\"},{\"title\":\"Inside Man\",\"year\":2006,\"type\":\"movie\"},{\"title\":\"The Town\",\"year\":2010,\"typ"
    "e\":\"movie\"},{\"title\":\"Baby Driver\",\"year\":2017,\"type\":\"movie\"}]},{\"id\":\"feel-good-comfort-movies\",\"t"
    "itle\":\"Feel-Good Comfort Movies\",\"subtitle\":\"Heartwarming and uplifting stories that always bring a "
    "smile.\",\"kind\":\"theme\",\"symbol\":\"sun.max.fill\",\"tint\":\"yellow\",\"source\":null,\"items\":[{\"title\":\"Sing"
    "in' in the Rain\",\"year\":1952,\"type\":\"movie\"},{\"title\":\"The Sound of Music\",\"year\":1965,\"type\":\"movie"
    "\"},{\"title\":\"Ferris Bueller's Day Off\",\"year\":1986,\"type\":\"movie\"},{\"title\":\"The Princess Bride\",\"ye"
    "ar\":1987,\"type\":\"movie\"},{\"title\":\"Groundhog Day\",\"year\":1993,\"type\":\"movie\"},{\"title\":\"Mrs. Doubtfi"
    "re\",\"year\":1993,\"type\":\"movie\"},{\"title\":\"Amélie\",\"year\":2001,\"type\":\"movie\"},{\"title\":\"School of Ro"
    "ck\",\"year\":2003,\"type\":\"movie\"},{\"title\":\"Little Miss Sunshine\",\"year\":2006,\"type\":\"movie\"},{\"title\""
    ":\"Fantastic Mr. Fox\",\"year\":2009,\"type\":\"movie\"},{\"title\":\"The Intouchables\",\"year\":2011,\"type\":\"mov"
    "ie\"},{\"title\":\"Chef\",\"year\":2014,\"type\":\"movie\"},{\"title\":\"Hunt for the Wilderpeople\",\"year\":2016,\"t"
    "ype\":\"movie\"},{\"title\":\"Paddington 2\",\"year\":2017,\"type\":\"movie\"},{\"title\":\"CODA\",\"year\":2021,\"type\""
    ":\"movie\"}]},{\"id\":\"edge-of-your-seat-thrillers\",\"title\":\"Edge-of-Your-Seat Thrillers\",\"subtitle\":\"Gr"
    "ipping suspense and relentless tension from beginning to end.\",\"kind\":\"theme\",\"symbol\":\"bolt.heart.f"
    "ill\",\"tint\":\"red\",\"source\":null,\"items\":[{\"title\":\"Rear Window\",\"year\":1954,\"type\":\"movie\"},{\"title\""
    ":\"Vertigo\",\"year\":1958,\"type\":\"movie\"},{\"title\":\"Psycho\",\"year\":1960,\"type\":\"movie\"},{\"title\":\"Jaws\""
    ",\"year\":1975,\"type\":\"movie\"},{\"title\":\"The Silence of the Lambs\",\"year\":1991,\"type\":\"movie\"},{\"title"
    "\":\"The Fugitive\",\"year\":1993,\"type\":\"movie\"},{\"title\":\"Seven\",\"year\":1995,\"type\":\"movie\"},{\"title\":\""
    "Fargo\",\"year\":1996,\"type\":\"movie\"},{\"title\":\"Memento\",\"year\":2000,\"type\":\"movie\"},{\"title\":\"Zodiac\","
    "\"year\":2007,\"type\":\"movie\"},{\"title\":\"No Country for Old Men\",\"year\":2007,\"type\":\"movie\"},{\"title\":\""
    "Prisoners\",\"year\":2013,\"type\":\"movie\"},{\"title\":\"Gone Girl\",\"year\":2014,\"type\":\"movie\"},{\"title\":\"Si"
    "cario\",\"year\":2015,\"type\":\"movie\"},{\"title\":\"Uncut Gems\",\"year\":2019,\"type\":\"movie\"}]},{\"id\":\"animat"
    "ed-films-for-adults\",\"title\":\"Animated Films for Adults\",\"subtitle\":\"Mature themes, bold artistry, a"
    "nd complex storytelling in animation.\",\"kind\":\"theme\",\"symbol\":\"paintpalette.fill\",\"tint\":\"indigo\",\""
    "source\":null,\"items\":[{\"title\":\"Fantastic Planet\",\"year\":1973,\"type\":\"movie\"},{\"title\":\"Watership Do"
    "wn\",\"year\":1978,\"type\":\"movie\"},{\"title\":\"Akira\",\"year\":1988,\"type\":\"movie\"},{\"title\":\"Grave of the "
    "Fireflies\",\"year\":1988,\"type\":\"movie\"},{\"title\":\"Ghost in the Shell\",\"year\":1995,\"type\":\"movie\"},{\"t"
    "itle\":\"Perfect Blue\",\"year\":1997,\"type\":\"movie\"},{\"title\":\"Princess Mononoke\",\"year\":1997,\"type\":\"mo"
    "vie\"},{\"title\":\"Waking Life\",\"year\":2001,\"type\":\"movie\"},{\"title\":\"The Triplets of Belleville\",\"year"
    "\":2003,\"type\":\"movie\"},{\"title\":\"Persepolis\",\"year\":2007,\"type\":\"movie\"},{\"title\":\"Waltz with Bashir"
    "\",\"year\":2008,\"type\":\"movie\"},{\"title\":\"Mary and Max\",\"year\":2009,\"type\":\"movie\"},{\"title\":\"Anomalis"
    "a\",\"year\":2015,\"type\":\"movie\"},{\"title\":\"I Lost My Body\",\"year\":2019,\"type\":\"movie\"},{\"title\":\"Flee\""
    ",\"year\":2021,\"type\":\"movie\"}]},{\"id\":\"great-documentaries\",\"title\":\"Great Documentaries\",\"subtitle\":"
    "\"Compelling non-fiction cinema exploring real lives, art, and history.\",\"kind\":\"theme\",\"symbol\":\"cam"
    "era.macro\",\"tint\":\"teal\",\"source\":null,\"items\":[{\"title\":\"Shoah\",\"year\":1985,\"type\":\"movie\"},{\"title"
    "\":\"The Thin Blue Line\",\"year\":1988,\"type\":\"movie\"},{\"title\":\"Hoop Dreams\",\"year\":1994,\"type\":\"movie\""
    "},{\"title\":\"March of the Penguins\",\"year\":2005,\"type\":\"movie\"},{\"title\":\"Grizzly Man\",\"year\":2005,\"t"
    "ype\":\"movie\"},{\"title\":\"Man on Wire\",\"year\":2008,\"type\":\"movie\"},{\"title\":\"Jiro Dreams of Sushi\",\"ye"
    "ar\":2011,\"type\":\"movie\"},{\"title\":\"The Act of Killing\",\"year\":2012,\"type\":\"movie\"},{\"title\":\"Amy\",\"y"
    "ear\":2015,\"type\":\"movie\"},{\"title\":\"Won't You Be My Neighbor?\",\"year\":2018,\"type\":\"movie\"},{\"title\":"
    "\"Free Solo\",\"year\":2018,\"type\":\"movie\"},{\"title\":\"Honeyland\",\"year\":2019,\"type\":\"movie\"},{\"title\":\"S"
    "ummer of Soul\",\"year\":2021,\"type\":\"movie\"},{\"title\":\"Fire of Love\",\"year\":2022,\"type\":\"movie\"},{\"tit"
    "le\":\"20 Days in Mariupol\",\"year\":2023,\"type\":\"movie\"}]},{\"id\":\"space-and-beyond\",\"title\":\"Space and "
    "Beyond\",\"subtitle\":\"Cosmic journeys, interstellar exploration, and the vast unknown.\",\"kind\":\"theme\""
    ",\"symbol\":\"moon.stars.fill\",\"tint\":\"blue\",\"source\":null,\"items\":[{\"title\":\"2001: A Space Odyssey\",\"y"
    "ear\":1968,\"type\":\"movie\"},{\"title\":\"Solaris\",\"year\":1972,\"type\":\"movie\"},{\"title\":\"Alien\",\"year\":197"
    "9,\"type\":\"movie\"},{\"title\":\"The Right Stuff\",\"year\":1983,\"type\":\"movie\"},{\"title\":\"Apollo 13\",\"year\""
    ":1995,\"type\":\"movie\"},{\"title\":\"Contact\",\"year\":1997,\"type\":\"movie\"},{\"title\":\"Sunshine\",\"year\":2007"
    ",\"type\":\"movie\"},{\"title\":\"Moon\",\"year\":2009,\"type\":\"movie\"},{\"title\":\"Gravity\",\"year\":2013,\"type\":\""
    "movie\"},{\"title\":\"Interstellar\",\"year\":2014,\"type\":\"movie\"},{\"title\":\"The Martian\",\"year\":2015,\"type"
    "\":\"movie\"},{\"title\":\"Arrival\",\"year\":2016,\"type\":\"movie\"},{\"title\":\"Hidden Figures\",\"year\":2016,\"typ"
    "e\":\"movie\"},{\"title\":\"First Man\",\"year\":2018,\"type\":\"movie\"},{\"title\":\"Ad Astra\",\"year\":2019,\"type\":"
    "\"movie\"}]},{\"id\":\"time-loop-stories\",\"title\":\"Time-Loop Stories\",\"subtitle\":\"Endless cycles, repeati"
    "ng days, and desperate struggles to break free.\",\"kind\":\"theme\",\"symbol\":\"arrow.triangle.2.circlepat"
    "h\",\"tint\":\"cyan\",\"source\":null,\"items\":[{\"title\":\"Groundhog Day\",\"year\":1993,\"type\":\"movie\"},{\"title"
    "\":\"12:01\",\"year\":1993,\"type\":\"movie\"},{\"title\":\"Retroactive\",\"year\":1997,\"type\":\"movie\"},{\"title\":\"R"
    "un Lola Run\",\"year\":1998,\"type\":\"movie\"},{\"title\":\"Primer\",\"year\":2004,\"type\":\"movie\"},{\"title\":\"The"
    " Butterfly Effect\",\"year\":2004,\"type\":\"movie\"},{\"title\":\"Triangle\",\"year\":2009,\"type\":\"movie\"},{\"tit"
    "le\":\"Source Code\",\"year\":2011,\"type\":\"movie\"},{\"title\":\"Looper\",\"year\":2012,\"type\":\"movie\"},{\"title\""
    ":\"Edge of Tomorrow\",\"year\":2014,\"type\":\"movie\"},{\"title\":\"ARQ\",\"year\":2016,\"type\":\"movie\"},{\"title\":"
    "\"Before I Fall\",\"year\":2017,\"type\":\"movie\"},{\"title\":\"Happy Death Day\",\"year\":2017,\"type\":\"movie\"},{"
    "\"title\":\"Russian Doll\",\"year\":2019,\"type\":\"series\"},{\"title\":\"Palm Springs\",\"year\":2020,\"type\":\"movi"
    "e\"}]},{\"id\":\"coming-of-age\",\"title\":\"Coming of Age\",\"subtitle\":\"Stories of growing up, identity, hea"
    "rtbreak, and the road to adulthood.\",\"kind\":\"theme\",\"symbol\":\"figure.walk\",\"tint\":\"green\",\"source\":n"
    "ull,\"items\":[{\"title\":\"The 400 Blows\",\"year\":1959,\"type\":\"movie\"},{\"title\":\"The Graduate\",\"year\":196"
    "7,\"type\":\"movie\"},{\"title\":\"Stand by Me\",\"year\":1986,\"type\":\"movie\"},{\"title\":\"Dead Poets Society\",\""
    "year\":1989,\"type\":\"movie\"},{\"title\":\"Dazed and Confused\",\"year\":1993,\"type\":\"movie\"},{\"title\":\"Almos"
    "t Famous\",\"year\":2000,\"type\":\"movie\"},{\"title\":\"Juno\",\"year\":2007,\"type\":\"movie\"},{\"title\":\"The Perk"
    "s of Being a Wallflower\",\"year\":2012,\"type\":\"movie\"},{\"title\":\"Boyhood\",\"year\":2014,\"type\":\"movie\"},"
    "{\"title\":\"Moonlight\",\"year\":2016,\"type\":\"movie\"},{\"title\":\"Lady Bird\",\"year\":2017,\"type\":\"movie\"},{\""
    "title\":\"Call Me by Your Name\",\"year\":2017,\"type\":\"movie\"},{\"title\":\"Eighth Grade\",\"year\":2018,\"type\""
    ":\"movie\"},{\"title\":\"Booksmart\",\"year\":2019,\"type\":\"movie\"},{\"title\":\"Aftersun\",\"year\":2022,\"type\":\"m"
    "ovie\"}]},{\"id\":\"modern-horror\",\"title\":\"Modern Horror Essentials\",\"subtitle\":\"Chilling, visionary, a"
    "nd psychological horror defining contemporary cinema.\",\"kind\":\"theme\",\"symbol\":\"flame.fill\",\"tint\":\""
    "red\",\"source\":null,\"items\":[{\"title\":\"The Babadook\",\"year\":2014,\"type\":\"movie\"},{\"title\":\"It Follows"
    "\",\"year\":2014,\"type\":\"movie\"},{\"title\":\"The Witch\",\"year\":2015,\"type\":\"movie\"},{\"title\":\"Train to Bu"
    "san\",\"year\":2016,\"type\":\"movie\"},{\"title\":\"Get Out\",\"year\":2017,\"type\":\"movie\"},{\"title\":\"Hereditary"
    "\",\"year\":2018,\"type\":\"movie\"},{\"title\":\"A Quiet Place\",\"year\":2018,\"type\":\"movie\"},{\"title\":\"Midsomm"
    "ar\",\"year\":2019,\"type\":\"movie\"},{\"title\":\"Us\",\"year\":2019,\"type\":\"movie\"},{\"title\":\"The Invisible Ma"
    "n\",\"year\":2020,\"type\":\"movie\"},{\"title\":\"Talk to Me\",\"year\":2022,\"type\":\"movie\"},{\"title\":\"Nope\",\"ye"
    "ar\":2022,\"type\":\"movie\"},{\"title\":\"Pearl\",\"year\":2022,\"type\":\"movie\"},{\"title\":\"Barbarian\",\"year\":20"
    "22,\"type\":\"movie\"},{\"title\":\"Late Night with the Devil\",\"year\":2023,\"type\":\"movie\"}]},{\"id\":\"epic-hi"
    "storical-dramas\",\"title\":\"Epic Historical Dramas\",\"subtitle\":\"Grand scale, sweeping narratives, and "
    "dramatic turning points of history.\",\"kind\":\"theme\",\"symbol\":\"building.columns.fill\",\"tint\":\"brown\","
    "\"source\":null,\"items\":[{\"title\":\"Lawrence of Arabia\",\"year\":1962,\"type\":\"movie\"},{\"title\":\"Barry Lyn"
    "don\",\"year\":1975,\"type\":\"movie\"},{\"title\":\"The Last Emperor\",\"year\":1987,\"type\":\"movie\"},{\"title\":\"S"
    "chindler's List\",\"year\":1993,\"type\":\"movie\"},{\"title\":\"Braveheart\",\"year\":1995,\"type\":\"movie\"},{\"tit"
    "le\":\"Saving Private Ryan\",\"year\":1998,\"type\":\"movie\"},{\"title\":\"Gladiator\",\"year\":2000,\"type\":\"movie"
    "\"},{\"title\":\"Master and Commander: The Far Side of the World\",\"year\":2003,\"type\":\"movie\"},{\"title\":\""
    "There Will Be Blood\",\"year\":2007,\"type\":\"movie\"},{\"title\":\"Lincoln\",\"year\":2012,\"type\":\"movie\"},{\"ti"
    "tle\":\"12 Years a Slave\",\"year\":2013,\"type\":\"movie\"},{\"title\":\"Dunkirk\",\"year\":2017,\"type\":\"movie\"},{"
    "\"title\":\"1917\",\"year\":2019,\"type\":\"movie\"},{\"title\":\"Killers of the Flower Moon\",\"year\":2023,\"type\":"
    "\"movie\"},{\"title\":\"Oppenheimer\",\"year\":2023,\"type\":\"movie\"}]},{\"id\":\"courtroom-dramas\",\"title\":\"Cour"
    "troom Dramas\",\"subtitle\":\"Tense cross-examinations, legal battles, and the search for justice.\",\"kin"
    "d\":\"theme\",\"symbol\":\"scalemass.fill\",\"tint\":\"mint\",\"source\":null,\"items\":[{\"title\":\"12 Angry Men\",\"y"
    "ear\":1957,\"type\":\"movie\"},{\"title\":\"Witness for the Prosecution\",\"year\":1957,\"type\":\"movie\"},{\"title"
    "\":\"Anatomy of a Murder\",\"year\":1959,\"type\":\"movie\"},{\"title\":\"Inherit the Wind\",\"year\":1960,\"type\":\""
    "movie\"},{\"title\":\"Judgment at Nuremberg\",\"year\":1961,\"type\":\"movie\"},{\"title\":\"To Kill a Mockingbird"
    "\",\"year\":1962,\"type\":\"movie\"},{\"title\":\"The Verdict\",\"year\":1982,\"type\":\"movie\"},{\"title\":\"A Few Goo"
    "d Men\",\"year\":1992,\"type\":\"movie\"},{\"title\":\"Philadelphia\",\"year\":1993,\"type\":\"movie\"},{\"title\":\"Pri"
    "mal Fear\",\"year\":1996,\"type\":\"movie\"},{\"title\":\"Erin Brockovich\",\"year\":2000,\"type\":\"movie\"},{\"title"
    "\":\"Michael Clayton\",\"year\":2007,\"type\":\"movie\"},{\"title\":\"Bridge of Spies\",\"year\":2015,\"type\":\"movie"
    "\"},{\"title\":\"The Trial of the Chicago 7\",\"year\":2020,\"type\":\"movie\"},{\"title\":\"Anatomy of a Fall\",\"y"
    "ear\":2023,\"type\":\"movie\"}]},{\"id\":\"food-on-film\",\"title\":\"Food on Film\",\"subtitle\":\"Culinary passion"
    ", exquisite flavors, and the communal warmth of dining.\",\"kind\":\"theme\",\"symbol\":\"fork.knife\",\"tint\""
    ":\"orange\",\"source\":null,\"items\":[{\"title\":\"Tampopo\",\"year\":1985,\"type\":\"movie\"},{\"title\":\"Babette's "
    "Feast\",\"year\":1987,\"type\":\"movie\"},{\"title\":\"Like Water for Chocolate\",\"year\":1992,\"type\":\"movie\"},{"
    "\"title\":\"Eat Drink Man Woman\",\"year\":1994,\"type\":\"movie\"},{\"title\":\"Big Night\",\"year\":1996,\"type\":\"m"
    "ovie\"},{\"title\":\"Chocolat\",\"year\":2000,\"type\":\"movie\"},{\"title\":\"Ratatouille\",\"year\":2007,\"type\":\"mo"
    "vie\"},{\"title\":\"Julie & Julia\",\"year\":2009,\"type\":\"movie\"},{\"title\":\"Jiro Dreams of Sushi\",\"year\":20"
    "11,\"type\":\"movie\"},{\"title\":\"Chef\",\"year\":2014,\"type\":\"movie\"},{\"title\":\"The Hundred-Foot Journey\",\""
    "year\":2014,\"type\":\"movie\"},{\"title\":\"Boiling Point\",\"year\":2021,\"type\":\"movie\"},{\"title\":\"The Bear\","
    "\"year\":2022,\"type\":\"series\"},{\"title\":\"The Menu\",\"year\":2022,\"type\":\"movie\"},{\"title\":\"The Taste of "
    "Things\",\"year\":2023,\"type\":\"movie\"}]},{\"id\":\"prestige-tv-miniseries\",\"title\":\"Prestige TV Miniseries"
    "\",\"subtitle\":\"Limited television series that deliver ambitious, cinematic stories.\",\"kind\":\"theme\",\""
    "symbol\":\"tv.fill\",\"tint\":\"purple\",\"source\":null,\"items\":[{\"title\":\"Roots\",\"year\":1977,\"type\":\"series"
    "\"},{\"title\":\"Lonesome Dove\",\"year\":1989,\"type\":\"series\"},{\"title\":\"Band of Brothers\",\"year\":2001,\"ty"
    "pe\":\"series\"},{\"title\":\"Angels in America\",\"year\":2003,\"type\":\"series\"},{\"title\":\"John Adams\",\"year\""
    ":2008,\"type\":\"series\"},{\"title\":\"The Pacific\",\"year\":2010,\"type\":\"series\"},{\"title\":\"The Night Of\",\""
    "year\":2016,\"type\":\"series\"},{\"title\":\"Chernobyl\",\"year\":2019,\"type\":\"series\"},{\"title\":\"When They Se"
    "e Us\",\"year\":2019,\"type\":\"series\"},{\"title\":\"Watchmen\",\"year\":2019,\"type\":\"series\"},{\"title\":\"The Qu"
    "een's Gambit\",\"year\":2020,\"type\":\"series\"},{\"title\":\"Mare of Easttown\",\"year\":2021,\"type\":\"series\"},"
    "{\"title\":\"Station Eleven\",\"year\":2021,\"type\":\"series\"},{\"title\":\"Dopesick\",\"year\":2021,\"type\":\"serie"
    "s\"},{\"title\":\"Beef\",\"year\":2023,\"type\":\"series\"}]},{\"id\":\"comfort-sitcoms\",\"title\":\"Comfort Sitcoms\""
    ",\"subtitle\":\"Warm ensembles, familiar living rooms, and endlessly rewatchable laughs.\",\"kind\":\"theme"
    "\",\"symbol\":\"sofa.fill\",\"tint\":\"pink\",\"source\":null,\"items\":[{\"title\":\"The Golden Girls\",\"year\":1985,"
    "\"type\":\"series\"},{\"title\":\"Seinfeld\",\"year\":1989,\"type\":\"series\"},{\"title\":\"The Fresh Prince of Bel-"
    "Air\",\"year\":1990,\"type\":\"series\"},{\"title\":\"Frasier\",\"year\":1993,\"type\":\"series\"},{\"title\":\"Friends\""
    ",\"year\":1994,\"type\":\"series\"},{\"title\":\"That '70s Show\",\"year\":1998,\"type\":\"series\"},{\"title\":\"Malco"
    "lm in the Middle\",\"year\":2000,\"type\":\"series\"},{\"title\":\"Scrubs\",\"year\":2001,\"type\":\"series\"},{\"titl"
    "e\":\"The Office\",\"year\":2005,\"type\":\"series\"},{\"title\":\"How I Met Your Mother\",\"year\":2005,\"type\":\"se"
    "ries\"},{\"title\":\"Parks and Recreation\",\"year\":2009,\"type\":\"series\"},{\"title\":\"Community\",\"year\":2009"
    ",\"type\":\"series\"},{\"title\":\"Modern Family\",\"year\":2009,\"type\":\"series\"},{\"title\":\"New Girl\",\"year\":2"
    "011,\"type\":\"series\"},{\"title\":\"Brooklyn Nine-Nine\",\"year\":2013,\"type\":\"series\"}]},{\"id\":\"french-cine"
    "ma-essentials\",\"title\":\"French Cinema Essentials\",\"subtitle\":\"Landmark classics and contemporary gem"
    "s of French filmmaking.\",\"kind\":\"theme\",\"symbol\":\"film.stack\",\"tint\":\"blue\",\"source\":null,\"items\":[{"
    "\"title\":\"The Rules of the Game\",\"year\":1939,\"type\":\"movie\"},{\"title\":\"Children of Paradise\",\"year\":1"
    "945,\"type\":\"movie\"},{\"title\":\"The 400 Blows\",\"year\":1959,\"type\":\"movie\"},{\"title\":\"Breathless\",\"year"
    "\":1960,\"type\":\"movie\"},{\"title\":\"Cléo from 5 to 7\",\"year\":1962,\"type\":\"movie\"},{\"title\":\"Playtime\",\""
    "year\":1967,\"type\":\"movie\"},{\"title\":\"Belle de Jour\",\"year\":1967,\"type\":\"movie\"},{\"title\":\"La Haine\","
    "\"year\":1995,\"type\":\"movie\"},{\"title\":\"Beau Travail\",\"year\":1999,\"type\":\"movie\"},{\"title\":\"Amélie\",\"y"
    "ear\":2001,\"type\":\"movie\"},{\"title\":\"A Prophet\",\"year\":2009,\"type\":\"movie\"},{\"title\":\"The Intouchable"
    "s\",\"year\":2011,\"type\":\"movie\"},{\"title\":\"Portrait of a Lady on Fire\",\"year\":2019,\"type\":\"movie\"},{\"t"
    "itle\":\"Petite Maman\",\"year\":2021,\"type\":\"movie\"},{\"title\":\"Anatomy of a Fall\",\"year\":2023,\"type\":\"mo"
    "vie\"}]}]}";
    return [NSData dataWithBytesNoCopy:(void *)json length:sizeof(json) - 1 freeWhenDone:NO];
}
